// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OrderScribleRepositoryInterface is an autogenerated mock type for the OrderScribleRepositoryInterface type
type OrderScribleRepositoryInterface struct {
	mock.Mock
}

// FindUserRefreshToken provides a mock function with given fields: id
func (_m *OrderScribleRepositoryInterface) FindUserRefreshToken(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindWorkshopRefreshToken provides a mock function with given fields: id
func (_m *OrderScribleRepositoryInterface) FindWorkshopRefreshToken(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
