// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WorkshopScribleRepositoryInterface is an autogenerated mock type for the WorkshopScribleRepositoryInterface type
type WorkshopScribleRepositoryInterface struct {
	mock.Mock
}

// DeleteWorkshopRefreshToken provides a mock function with given fields: workshopID
func (_m *WorkshopScribleRepositoryInterface) DeleteWorkshopRefreshToken(workshopID string) error {
	ret := _m.Called(workshopID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(workshopID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindWorkshopRefreshToken provides a mock function with given fields: workshopID
func (_m *WorkshopScribleRepositoryInterface) FindWorkshopRefreshToken(workshopID string) error {
	ret := _m.Called(workshopID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(workshopID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
