// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UserScribleRepositoryInterface is an autogenerated mock type for the UserScribleRepositoryInterface type
type UserScribleRepositoryInterface struct {
	mock.Mock
}

// DeleteUserRefreshToken provides a mock function with given fields: userID
func (_m *UserScribleRepositoryInterface) DeleteUserRefreshToken(userID string) error {
	ret := _m.Called(userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUserRefreshToken provides a mock function with given fields: userID
func (_m *UserScribleRepositoryInterface) FindUserRefreshToken(userID string) error {
	ret := _m.Called(userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
