name: Testing CI
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  # job 1: unit test
  unit-test:
    name: do unit test project gorepair
    runs-on: ubuntu-latest
    steps:
      - name: setup github action #in order to run setup github action first
        uses: actions/checkout@v2
      - name: set-up golang
        uses: action/setup-go@v2
        with:
          go-version: 1.17
      - name: running unit test
        run: go test ./... -cover
